abbvie-external/OmicNavigatorWebApp

- src/components/Differential/DifferentialSearchCriteria.jsx
- src/components/Enrichment/EnrichmentSearchCriteria.jsx
- fix study analysis tooltip text
- call getReportLink once on reload
> Ipad 284 study fixes

- src/components/Differential/DifferentialSearchCriteria.jsx
- src/components/Enrichment/EnrichmentSearchCriteria.jsx
- adds study tooltips based on the package descriptions
> study tooltips

- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/FilteredDifferentialTable.jsx
- adds favicons to the filtered differential table (enrichment tab, triple plot view)
> Ipad 305 favicons triple panel

- .github/workflows/dev.yml
- .github/workflows/release.yml
> Fix deploy-dev workflow

- src/components/App.scss
- src/components/Tabs.jsx
- Adds help modal (requirements [IPAD-299](https://jira.abbvienet.com/browse/IPAD-299))
> Ipad 299 help modal

- src/components/Differential/DifferentialPlot.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/MetafeaturesTable.jsx
feature data table: 
- add export buttons (TXT, XLS) that use a Ref and match the rest of the app
- enable search
> Ipad 303 metafeatures export button

- package-lock.json
- package.json
- public/manifest.json
- src/components/App.jsx
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialPlot.jsx
- src/components/Differential/DifferentialSearchCriteria.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSVGPlot.jsx
- src/components/Enrichment/EnrichmentSearchCriteria.jsx
- src/components/Shared/QHGrid/index.js
- src/components/Shared/SVGPlot.jsx
- src/components/Tabs.jsx
- fix relevant volcano cols
- clean up eslint and console warnings
- bump version for release
> Bump app version

- src/components/Differential/DifferentialVolcano.jsx
- for multi-feature plotting, use the filtered/sorted data, not just current data
> use sorted data

- src/components/Differential/DifferentialVolcanoPlot.jsx
Updates the bin click event (line 269) to render the bin as circle elements and removes the bin
> Ipad 314 hex explode without zoom

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/DifferentialVolcanoPlot.jsx
- fix volcano single click with filtered data
> fix single click with filtered data

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/DifferentialVolcanoPlot.jsx
- use ctrl + click or cmd + click (Mac users) to highlight circles in volcanoPlot
- Bins will NOT explode when ctrl + click or cmd + click is used
- Highlighted bins will persist if bins are exploded
> Ipad 320 click multiple circles bins

- src/components/Differential/DifferentialVolcanoPlot.jsx
Refactored transform function to calculate the text element width.  
If it's greater than the width of the volcano chart render on left side of circle element.
> Ipad 317 clip path box select periphery export fix

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialMultisetFilters.jsx
- src/components/Differential/DifferentialSearchCriteria.jsx
- src/services/omicNavigator.service.js
- Differential multiset analysis dropdowns driven off of getUpsetCols endpoint (rather than only the numeric columns)
> Ipad 329 get upset cols fe

- src/components/Differential/DifferentialVolcanoPlot.jsx
- added more height to account for x axis label getting truncated when exported
- added inline font style to stay consistent when exported
> fixes font issue and x axis truncation on export

- src/components/Differential/DifferentialVolcanoPlot.jsx
- Fixes bug where a single click deselect on a point in scatterplot or on table does not always remove label
- Circle labels are now retained after zoom
> Ipad 322 label bugs

- src/components/Enrichment/Enrichment.jsx
-  refresh enrichment table columns when favicons return
> Ipad 266 favicons refactor

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialPlot.jsx
- src/components/Differential/MetafeaturesTable.jsx
- enables ability to display multiple, multi-feature plots
- can test with W210488.Hs.Human.skin.LCM.proteomics when author fixes function for the PCA plot (currently throws an error); no other studies use multiple multi-feature plots yet
> Ipad 341 enable multiple mulitfeature plots

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/DifferentialVolcano.scss
- Remove arrow icon from "select all" column header
- Extend the select all checkbox functionality by clicking the entire cell.
- Needed to create a div element to fill the cell and add the "toggleAllCheckboxes" to its click event.
> Update select all checkbox

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialSearch.jsx
- src/components/Differential/ScatterPlot.jsx
- src/components/Enrichment/Enrichment.jsx
I'm working on a larger refactor for this task that will address performance across all scatter plot interactions (notably double-click zoom out), but that will take some more time to finish/test.  In the meantime, I'd like to merge this "quick fix" (pushed to Dev already so you/@bengalengel can test), so that we can at least load and interact with large studies like GTG590ClariomD.
> [IPAD-391] Scatter performance 50K (Quick Fix)

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialDetail.scss
- src/components/Differential/DifferentialSearch.jsx
- src/components/Differential/ScatterPlot.jsx
- src/components/Differential/ScatterPlot.scss
- Retain selected features after multi-set toggle
- Fix scatterplot y axis width
- Set scatterplot options dropdown width to auto
> [IPAD 391] - Address additional feedback

- src/components/Differential/Differential.jsx
- src/components/Differential/ScatterPlotDiv.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/FilteredDifferentialTable.jsx
- quick fix: default 'NA' data fallback for columns to numeric columns
> [IPAD-391] - Adjust multisetColsDifferential

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/DifferentialDetail.scss
- src/components/Differential/DifferentialSearch.jsx
- src/components/Differential/PlotlyMultiFeature.jsx
- src/components/Differential/PlotlyOverlay.jsx
- src/components/Differential/PlotlySingleFeature.jsx
- src/components/Differential/PlotsDynamic.scss
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSearch.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
- src/services/omicNavigator.service.js
Adds logic to call and display multi-model plots
Available for review in dev: differential/hiPSCmicrogliaWS4.1toN/transcriptomics/E2E2_E3E3
> [IPAD-408] Handle multi-model plots

- src/components/Differential/DifferentialDetail.jsx
Adds version 2 single-feature search: immediate case insensitive search across all alphanumeric columns.  
Available for review on DEV
> [IPAD-425] Single-feature search v2

- package-lock.json
- package.json
- public/manifest.json
- src/components/App.scss
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/DifferentialDetail.scss
- src/components/Differential/ScatterPlot.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
Adjusts search UI based on feedback (documented in JIRA) and extends multi-feature list search to be exact across all alphanumeric values.
> [IPAD-425] Add multi-feature list search v2

- package-lock.json
- package.json
- public/manifest.json
- src/components/App.scss
- src/components/Differential/DifferentialSearch.jsx
- src/components/Differential/PlotsDynamic.jsx
- src/components/Differential/PlotsSingleFeature.jsx
- src/components/Differential/ScatterPlot.jsx
- src/components/Enrichment/EnrichmentSearch.jsx
- src/components/Tabs.jsx
[431 ](https://jira.abbvienet.com/browse/IPAD-431) - Update the 'View Plot' info button text:
Just a text change
[432](https://jira.abbvienet.com/browse/IPAD-432) - Single Feature Plots to 'Single-Feature' Plots:
Just a text change
[433](https://jira.abbvienet.com/browse/IPAD-433) - can't see entire rectangle when a row is highlighted:
Just a CSS change
[434](https://jira.abbvienet.com/browse/IPAD-434) - Hover annotation isn't working after plot reset:
Just setting brushing state to false after a single or double-click on the scatter plot
These are reviewable in DEV, v1.8.0 
Note, there were not a lot of code changes for these tasks, but auto-formatting makes it appear there are.
> [IPAD-431/432/433/434] - Fix hover bug; renaming and styles

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Differential/Differential.scss
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/DifferentialSearch.jsx
- src/components/Differential/PlotsDynamic.jsx
- src/components/Differential/PlotsMultiFeature.jsx
- src/components/Differential/PlotsOverlay.jsx
- src/components/Differential/PlotsSingleFeature.jsx
- src/components/Differential/TabOverlay.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSVGPlot.jsx
- src/components/Enrichment/EnrichmentSearch.jsx
- src/components/Enrichment/FilteredDifferentialTable.jsx
- src/components/Enrichment/NetworkGraph.jsx
- src/components/Enrichment/SplitPanesContainer.jsx
- src/components/Shared/Search.scss
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
- src/components/Terms.jsx
- src/services/omicNavigator.service.js
1) Study report linkouts - change icon to "info"; when report exists, change icon color to orange and animate (shake)
2) For set analysis plot, change "View Plot" to "View Set Intersection"
3) For ALL plot dropdowns (differential dynamic plots, differential plots overlay, enrichment triple pane plot), on hover display a popup with the description (if exists - only demo study)
4) For the differential result
s table and filtered differential results table (in enrichment triple pane) columns, on hover display an html "title" tooltip with description (if exists - only demo study)
> [IPAD-446] Reviewer requests UI

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Tabs.jsx
Adjust the main container breakpoints so that our app doesn't stack content when a user is zoomed to 150% on a regular sized laptop.  I've merged to Dev with v1.8.5 for review
> [IPAD-448] remove breakpoints

- package-lock.json
- package.json
- public/manifest.json
- src/components/Enrichment/BarcodePlot.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSearch.jsx
- src/components/Tabs.jsx
BE adjusted to calculate/pass "lowest" statistic, which is used as the low stat for the barcode plot
> [IPAD-463] Barcode Plot - support negative statistics

- .vscode/settings.json
- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Tabs.jsx
- src/services/omicNavigator.service.js
Replaces opencpu `session.getLoc()` with base url and additional logic, so plot graphics append https on public server
> [IPAD-488] Fix plot errors public server

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/PlotlyMultiFeature.jsx
- src/components/Differential/PlotlyOverlay.jsx
- src/components/Differential/PlotlySingleFeature.jsx
- src/components/Differential/PlotsDynamic.jsx
- src/components/Differential/PlotsMultiFeature.jsx
- src/components/Differential/TabMultiFeature.jsx
- src/components/Differential/TabOverlay.jsx
- src/components/Differential/TabSingleFeature.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
See ticket description. Reviewable on Dev
> [IPAD-479] Common test check for multiModel multiTest plots

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialSearch.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSearch.jsx
- src/components/Tabs.jsx
> [IPAD-480][IPAD-481] - Fix enrichment tests refresh

- .vscode/settings.json
- package-lock.json
- src/components/Differential/ScatterPlot.jsx
> [IPAD-467] Fix scatterplot single point bug

- src/components/Enrichment/EnrichmentSearch.jsx
9 months ago I improperly altered the enrichmentStudyTooltip state (while adjusting enrichmentStudyReportTooltip)
> [IPAD-480] Fix enrichment study tooltip

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Tabs.jsx
> [IPAD-507] Fix multifeature plot fullscreen bug

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Differential/PlotlyMultiFeature.jsx
- src/components/Differential/PlotlyOverlay.jsx
- src/components/Differential/PlotlySingleFeature.jsx
- src/components/Differential/TabMultiFeature.jsx
- src/components/Differential/TabOverlay.jsx
- src/components/Differential/TabSingleFeature.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Tabs.jsx
- src/services/omicNavigator.service.js
> [IPAD-509] Plots refactor to support "model" arg and error messages from BE

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/TabMultiFeature.jsx
- src/components/Tabs.jsx
> [IPAD-509] fix typo

- package-lock.json
- package.json
- public/manifest.json
- src/components/Tabs.jsx
> [IPAD-537] Remove issues link
