- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialPlot.jsx
- src/components/Differential/DifferentialPlot.scss
- src/components/Enrichment/BarcodePlot.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSVGPlot.jsx
- src/components/Enrichment/SplitPanesContainer.scss
- src/components/Shared/SVGPlot.jsx
- src/components/Shared/SearchCriteria.scss
- src/components/Tabs.jsx
This PR just adds ids to svgs that were removed when react-inlinesvg was introduced.   They are needed to fix the 5 test suite failures, as well as fix both differential and enrichment multiset export (we should add exporting of all plots to the test suite)
> Ipad 293 diff analysis static plot dropdown

- .github/workflows/release.yml
This GitHub Action will trigger a new release of the R package bundled with the latest release of the web app.
Some requirements for this to work:
1. Both the tag and the release must be created in the GitHub UI for the action to be triggered. In other words, you can't run `git tag` locally and then later convert it to a release. @paulnordlund already creates the tags in GitHub, so this should work well.
2. The Action requires a repository secret named `REPO_ACCESS_TOKEN` that contains a PAT with repo access and is SSO authorized. @ternst23 already created and added this PAT, so it should work.
The corresponding Action in the R package repo that is triggered by this Action is [pin-app.yml](https://github.com/abbvie-external/OmicNavigator/blob/main/.github/workflows/pin-app.yml).
I had it …
> Add Action to trigger new release of R package.

- .github/workflows/dev.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
I realized it's harder than it should be for out internal CD workflows to know if they were triggered by the R package or web app repos. This PR makes it so that the dispatch events include more information about the workflow that sent them.
> Provide more info on triggering event in dispatch payload

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialSearchCriteria.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/MetafeaturesTable.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSearchCriteria.jsx
- src/components/Enrichment/FilteredDifferentialTable.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
- src/services/omicNavigator.service.js
- adds "&na="string" to all non-plot calls, so opencpu returns all properties even when the values are null
- add logic to get the first object with actual values (not NA/null/undefined) to use in order to distinguish between alphanumeric and numeric columns (used for table filter types, and to determine which are tests).
- fix multi-feature plots length bug (part of IPAD-234)
> Ipad 309 na data

- src/components/App.jsx
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialPlot.jsx
- src/components/Differential/DifferentialPlot.scss
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/DifferentialVolcanoPlot.jsx
- src/components/Differential/MetafeaturesTable.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Shared/helpers.jsx
- src/services/omicNavigator.service.js
- reverts plots in large "overlay" to call for xml and display that immediately (unlike resizable plot svgs, which return the url)
- adds race between a 10 second timeout and the multi-feature plot. If the timeout wins, a toast informs the user that the plot will open in a new tab when loaded
- limit multi-feature plotting to 1000 features
- add tooltip explaining the features to be plotted (first 1000 in table vs. all in table vs. highlighted)
- fixes shift-brush bug (nested data in "handleBrushedText")
> Ipad 234 multi feature timeouts

- src/components/Differential/DifferentialVolcanoPlot.jsx
- Adds more height and width to clip path and brush extent to allow easier box select on elements in the periphery of the plot
- Above fix also address circles/bins getting cut off by the clip path
- Fixes tooltip issue where tooltip overlaps the ticks on the x axis
> fixes box select and circle edges getting cut off

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialPlot.jsx
- src/components/Differential/MetafeaturesTable.jsx
- Fix feature data in the differential overlay (plots + feature data).  Sometimes the data should have existed but "getMetaFeaturesTable" wasn't called at all because "allMetaFeaturesDataDifferential" hadn't been returned.  I've moved "getMetaFeaturesTable" to a lower child component and am using async await.
- Remove unnecessary checks for "multifeature" plots, which are using multifeature specific functions recently added.
- Can test with RNAseq123, that has feature data: http://localhost:3000/#/differential/RNAseq123/Differential_Expression/BasalvsLP
> async feature data, move to child

- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/DifferentialVolcanoPlot.jsx
- removes highlight code from "endBrush" function to fix gray (filtered) dots rerendering as blue
- created "volcanoCurrentState" global prop for use in "componentDidUpdate" function in DifferentialVolcano.jsx to keep table in sync with volcano plot.
- alters "setState" on line 300 to pass in empty values in order to clear the table for an empty dataset when filtered (gray) elements are box selected
- resets bin class to remove "highlighted" or "highlightedMax" if they were previously highlighted.
> Ipad 327 volcano box select behavior

- src/components/Differential/DifferentialVolcano.jsx
- src/components/Enrichment/SplitPanesContainer.jsx
- adjust volcano split panes so initial defaults and minimums don't cut off the x-axis label
- when a differential test changes, close the plot and set cache the current dimensions
> Ipad 321 pane dimensions stored

- src/components/Differential/DifferentialPlot.jsx
- src/components/Differential/MetafeaturesTable.jsx
- src/components/Shared/SVGPlot.scss
This PR does three things:
- caches the response data from getMetafeaturesTable for any given feature
- moves the getMetafeaturesTable call down to the table component itself where it is only called once (when it was higher it would get called again and again because the SVGs flow in one by one, and the call didn't have time to return/cache)
- fixes a bug with the dropdown index for "Feature Data", by reading the single plots length (filtering out multi-feature plot)
> Ipad 303 metafeatures caching

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialSearchCriteria.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/DifferentialVolcanoPlot.jsx
- src/components/Enrichment/Enrichment.jsx
- stores all test ids (on a study/model basis) in state, to be used for "multiTest" plot calls
- fix unintentional removal of single feature highlighting during pane drag (part of IPAD-349)
> Ipad 348 testids multitest plots

- src/components/Differential/Differential.jsx
- src/components/Enrichment/Enrichment.jsx
- checks for the inclusion of "multiFeature" in plotType, rather than equivalency, as the plotType may be an array (e.g. plotType: ['multiFeature', 'multiTest']) or a string (e.g. plotType: 'multiFeature')
> Ipad 348 multi test multi feature adjustment

- src/components/App.scss
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialVolcanoPlot.jsx
- src/components/Differential/SVGPlot.jsx
IPAD-375
1. results table feature blue hyperlinks active on default (displays active briefly when it shouldn't, e.g. study with "IPF.POC"), needs to change to false - modelSpecificMetaFeaturesExist: false
2. infinite "scatter plots" are loading - the Y axis label was allowed to stay null in one scenario
3. scatter plot not showing - the "Options" dropdowns used to be passed down as props, and it was slower, and Justin's code fires a change to the x axis dropdown to force a re-render. I'd moved everything down to the scatter plot level, and it's faster, so in some cases the x axis dropdown event fires, before data finishes streaming. I've adjusted the code to ensure rendering.
4. tabs message needs adjustment to look for feature data and plots, and display correct message
> fix scatter bugs; tabs message improvement

- package-lock.json
- package.json
- public/manifest.json
- src/components/App.scss
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialVolcano.jsx
- src/components/Differential/DifferentialVolcano.scss
- src/components/Differential/DifferentialVolcanoPlot.jsx
- src/components/Tabs.jsx
1) Added "Multi-Select Column" header to the multi-select column tooltip
2) Using a "cell" cursor and making checkbox outline orange 50% opacity when hovering in multi-select column.
3) when hovering over a cell, displaying a blue outline 50% opacity.  I could do the entire row like that, but the trade-off is that the multi-select cell hover will also trigger that effect, which is misleading (note there is no row onHover event built into QHGrid now).  I didn't find a way to override parent css, from a child.
4) B.E.'s top concern was that when the user has things highlighted/outlined (with no table sorting used), and then zooms in the scatter plot, the highlighted/outlined rows always get pushed to the bottom of the table/last page.  NOTE: this issue is not new, it exists in .141 with the …
> Ipad 349 selected plot improvements

- package-lock.json
- package.json
- public/manifest.json
- src/components/App.scss
- src/components/Tabs.jsx
- Fix CSS so the two tables in enrichment tab are not in scope
- Improve hover behavior: if multi-feature plotting is not available, add outline to entire row; if multi-feature plotting is available, add outline to cell (not first, which is the checkbox) and to adjacent cells: td:not(:first-child):hover ~ td. Note, this was the best solution without having to adjust external quick hits grid code, since in CSS children cannot alter parent elements.
> improve table row hover, fix scope, bump to v1.4.1

- src/services/omicNavigator.service.js
Adjusts service so that when one plot fails, the rest that succeed still populate.  You can test this by selecting feature ids "624245" and "22409" in the following study: "RNAseq123", model: "Differential_Expression", test: "BasalvsLP".  In .184 or .173 this will result in just 1 of 5 plots showing up, while with this fix, 4 of 5 plots will display. 
Dev note: Promise.allSettled wasn't waiting for all promises to be fulfilled/rejected because plots vs. plotly plots were being handled differently in the service.  I adjusted to use plotly to use try/catch and throw an error, which resolved the issue.
> [IPAD-379] Fix Plotly error handling

- src/components/Differential/ScatterPlot.jsx
Problem: When closing the scatterplot options popup, a click on the scatter plot itself inadvertently clears the multi-feature selection.
Solution: Add a flag to scatterplot click handling to ensure that the options popup is closed. If it is open, just return. Note, to support the flag, a slight timeout needed to be added when toggling options closed.
To test: Multi-select features. Click an empty part of the scatter plot and they should de-select. Do the same thing after opening the options popup. The features should remains selected.
> [AU-384] Scatterplot - ignore click when options open

- LICENSE
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/MetafeaturesTable.jsx
- src/components/Differential/MetafeaturesTableDynamic.jsx
- src/components/Differential/ScatterPlot.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/FilteredDifferentialTable.jsx
Adjusts table filter calculation (5 tables) to loop through each column (property) until it finds a real value.  Prior, we were looking for a row with data for all properties, and some studies (e.g. D04042022...) didn't fit that model.  This solution is more flexible and fast.  If a column has no real data at all, the column filter type will default to string.
> [IPAD-388] Add table support for columns wo/data

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/PlotlyMultiFeature.jsx
- src/components/Differential/PlotlyOverlay.jsx
- src/components/Differential/TabMultiFeature.jsx
- src/components/Differential/TabOverlay.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
Fixes Plotly plots with longer x-axis names that were getting cut off on full-screen and when exported.  Long labels were cutoff because we removed "auto-margins" that were "squishing" the entire plot in some instances (a known Plotly bug). Only "heatmaply" plot types show to be affected by the auto-margin issue, so for now, this PR adjusts the flag so all other plot types get auto-margins, and "heatmaply" just gets an additional hard-coded right margin of 50.
To test: first go to prod: /differential/RNAseq123/Differential_Expression/BasalvsLP
Under the symbol filters, click the top two results "0610009B22Rik".  Multi-select them. Click the "Full Screen" button. Notice on the "Expression Heatmap interactive with plotly" plot has labels cutoff in the view and export. Now go to this branch, …
> [IPAD-386] - Plotly axis cutoff

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Tabs.jsx
Fix bug with cached data by moving the column config flag from async state to sync this.
To test: select any study/model/test combination. Switch to another a different study/model/test combo.  Navigate back to the first and confirm the columns are correct.
> [IPAD-400] Move column config flag

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/DifferentialSearch.jsx
- src/components/Differential/ScatterPlotDiv.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
Scatterplot axis labels are cached for a given study/model/test.  However, when they are first set, we "sniff" for certain values.  The way this was coded looks for a variety of different values, but in their entirety (**indexOf**), not substrings of them.  So labels like PValue.Blah wouldn't get picked up, and the fallback is the zero index of the columns array.  I've changed the code to look for the inclusion of substrings, so PValue.Blah will be valid for the default. To make this easier, I **lowercase** the columns, and run **.includes**.
Now we are sniffing for:
1) Scatterplot "X Axis":   logfc, log.fc, log2fc, foldchange, fold change, fc, log
2) Scatterplot "Y Axis": pval, p.val, p_val, p val, adjpval, adj.p.val, adj_p_val, adj p val
3) Multiset "Column": pval, p.val, p_val, p val, …
> [IPAD-401] Scatterplot axis & multiset column defaults

- src/components/Differential/ScatterPlot.jsx
- src/components/Enrichment/BarcodePlot.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/ViolinPlot.jsx
The semi-colons in the feature ids for study "Liver Tropism" were causing breaking errors in the enrichment triple-pane view. I'm not sure why semi-colons within CSS selectors are considered invalid (like period or space - which would represent a class, or a child), however the change to this alternative CSS selection method fixed the issues.
Example: Before - d3.select('#barcode-line-featureId'); After - d3.select('line[id="barcode-line-featureId"]')
Note: you can review on .173 (go/on-dev), where I've merged the branch to facilitate testing
> [IPAD-403] - Fix d3.select invalid selectors

- src/components/Differential/DifferentialSearch.jsx
- src/components/Enrichment/EnrichmentSearch.jsx
I cannot replicate the bug for [IPAD-404](https://jira.abbvienet.com/browse/IPAD-404) locally on .184 nor .173.  However, we can tell that the columns are not being re-configured when returning to a study/model/db that already has cached enrichment results table.  This PR just sets the columns configured value back to false after a model is changed, since doing it on test/database change doesn't seem to be enough.
> [IPAD-404] - cached enrichment results config columns bug

- package-lock.json
- package.json
- public/manifest.json
- src/components/Enrichment/BarcodePlot.jsx
- src/components/Tabs.jsx
Duplicated issue every time when a scatter plot is in view, and then a barcode plot is rendered.  There is a function that removes the d3 element class 'overlay' and it is too general; the overlay for the scatter plot exists in the DOM and is removed. To fix, I've specified the specific overlay to remove:  d3.select('.barcodeBrush rect.overlay').remove();
> [IPAD-402] Fix brush bug

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/ScatterPlot.jsx
- src/components/Tabs.jsx
In datasets with fewer than 2500 features, `circles` and `relevantCircles` state wasn't being set for the scatterplot, and therefore couldn't be read for labels.
To test: ensure scatter plot circle labels work for datasets with fewer than 2500 features, for example: http://localhost:3000/#/differential/D07282022.D20210927.W210488.Hs.Human.skin.LCM/Protein_Expression/Epidermis.vs.HS_Epithelium
> [IPAD-410] Fix scatter plot label bug

- src/components/Enrichment/Enrichment.jsx
Allows column refresh when favicons are available. This is only for enrichment; the trade-off is too high for differential.
To test, clear local storage, then go to http://localhost:3000/#/enrichment/RCD/ferro_v_untreated.  Click through different annotations, and if the first time a favicon appears it is generic (solid grey with white arrow), wait a few seconds and it will change to an actual icon.
> [IPAD-394] Refresh favicons

- package-lock.json
- package.json
- public/manifest.json
- src/components/Enrichment/NetworkGraph.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
Handle undefined p-values in the network graph. To test, in the network graph, hover over a node with a grey pie (undefined). For example: http://localhost:3000/#/enrichment/D07282022.D20210927.W210488.Hs.Human.skin.LCM/VisiumHS/GO_enrich
> [IPAD_421] Fix network graph bug

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/MetafeaturesTable.jsx
- src/components/Differential/MetafeaturesTableDynamic.jsx
- src/components/Differential/PlotsOverlay.jsx
- src/components/Differential/PlotsSingleFeature.jsx
- src/components/Differential/TabOverlay.jsx
- src/components/Differential/TabSingleFeature.jsx
- src/components/Enrichment/SplitPanesContainer.jsx
- src/components/Tabs.jsx
**Bug**: Export of the feature data tables was broken in both the dynamic triple pane and the overlay, because the reference ("ref") was undefined
**Fix**: use React's "forwardRef" to allow the child component to pass the table ref to it's parent/s
**Test**: export both .xls and .txt in the following views:
dynamic triple pane:
overlay:
> [IPAD-424] Fix export of feature metadata

- src/components/Enrichment/BarcodePlot.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/FilteredDifferentialTable.jsx
- src/components/Enrichment/SplitPanesContainer.jsx
- src/components/Enrichment/SplitPanesContainer.scss
- src/services/omicNavigator.service.js
Adjusts logic so that studies without barcode data will still display statistics table and SVG plots.  
The statistics table used to be a subset of the getResultsTable and getBarcodeData.  However, with getResultsTable updated to take optional arguments (annotationID, termID), we can just use those results to display the statistics table.
To test, try studies both with barcode data (RNAseq123, and without (`enrichment/D07282022.D20210927.W210488.Hs.Human.skin.LCM/VisiumHS`)
I've merged this to DEV .173 for convenient review.
> [IPAD-411] Account for missing barcode

- src/components/Differential/Differential.jsx
- src/components/Shared/helpers.jsx
For `plotStudy` multiModel plots, adjust the "modelID" argument to place the model that is **currently selected** in the dropdown to the front of the array, rather than the model that is in the first index of the plotting object.  For example, if a study has 3 tests and the currently selected model is "Transcriptomics", the modelID argument should be `["Transcriptomics","Transcriptomics","Transcriptomics","Proteomics","Proteomics","Proteomics"]` rather than `["Proteomics","Proteomics","Proteomics","Transcriptomics","Transcriptomics","Transcriptomics"]`.
Please test the two studies with multi-model plots: 
1. differential/hiPSCmicrogliaWS4.1toN/transcriptomics
2. differential/W210229.CD40.B6.Mouse.Colon.Multiomics
> [IPAD-426] Adjust modelID argument for multiModel plotStudy calls

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/DifferentialDetail.jsx
- src/components/Tabs.jsx
Fix a non-breaking bug where the multi-feature list search text area and "Filtered out" section are not accurate.  It occurs in some situations when a table column filter is applied.  I made an oversight by only running a section of code (previously flagged by a state variable "eventFromTableColumnFilter" - this updates the multi-feature list search text area and "Filtered out" section) when the table re-rendered after a table filter event, when in actuality it should be run after other events, **accounting for table filters**.  With that in mind, I was also able to move and consolidate some code.
> [IPAD-429] Fix multi-feature search bug

- src/components/Differential/ScatterPlot.jsx
Problem: when zooming in the scatterplot **with a section containing a hexbin**, the table rows are reordered. It would be ideal if the default table sorting was maintained.
Solution: on zoom, take the existing table data and filter it by the new zoomed data, rather than just passing the new zoomed data, which has it's own, different order it recalculates if a hexbin is unbinned.
To test: DO A HARD REFRESH.  go to [prod](http://omicnavigator.ir-omicnavigator.awscloud.abbvienet.com/ocpu/library/OmicNavigator/www/#/differential/RNAseq123/Differential_Expression/BasalvsLP), set table 'items per page' to 10, notice the order of the table, and how it changes when a section including a hexbin is zoomed.  Note, you Next, go to [dev](http://10.253.152.173/ocpu/library/OmicNavigator/www/#/different …
> [IPAD-435] Retain table row order after scatterplot zoom

- src/components/Shared/helpers.jsx
I mentioned previously the front-end is ensuring that “the modelID argument must have the currently selected model in the first index of the vector”, so say, when the currently selected model is “transcriptomics”, part of the payload was sent like this: modelID: ["transcriptomics", "proteomics", "transcriptomics", "proteomics", "transcriptomics", "proteomics", "transcriptomics", "proteomics”], testID: ["E2E2_E3E3", "KO_E3E3", "E4E4_E3E3", "E3E4_E3E3", "E2E2_E3E3", "KO_E3E3", "E4E4_E3E3", "E3E4_E3E3"] 
This PR is to ensure the order of the vector of model ids match up correctly to each test id. The easiest way to accomplish that is to just repeat the first model, then repeat the second model, like this: modelID: ["transcriptomics", "transcriptomics", "transcriptomics", "transcriptomics", …
> [IPAD-439] Adjust modelIDs argument order

- src/components/Differential/TabMultiFeature.jsx
- src/components/Differential/TabSingleFeature.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/EnrichmentSVGPlot.jsx
Currently only "plotly" plots are displaying a message in the UI informing users a given plot isn't available.  Extend this message to all other plot types.
> [IPAD-441] Extent NA message to non-plotly plots

- src/components/Differential/DifferentialSearch.jsx
Problem: after performing "set analysis" with two or more variables, if you select another test then click "set analysis" again, the app crashes
Solution: reset `selectedOperatorP` state on test change
> [IPAD-440] Fix set analysis reset bug

- src/components/Differential/ScatterPlotDiv.jsx
In the scatterplot "options", users should have the ability to do a -log10 transformation on the data only when ALL NUMERIC DATA is greater than 0 for the selected option column.  For example, if the x-axis option is set to log2FC, if ANY row data is 0 or less, the transform checkbox should disabled and deactivated.  This fixes some holes in the code to ensure this, specifically the code only running a check for transformations when an options dropdown changed, rather than on test change (and caching situations).
> [IPAD-447] Fix transform flags

- src/components/Differential/DifferentialSearch.jsx
- src/components/Differential/ScatterPlot.jsx
- src/components/Differential/ScatterPlotDiv.jsx
- src/components/Enrichment/EnrichmentSearch.jsx
1) Changes "View Plot Intersections" to "View Set Intersections"
2) Hides "View Set Intersections" when "Set Analysis" is turned off
3) Fixes bug - when set analysis "Filter" was pressed for the first time, the table would filter but the scatterplot would not.  The only thing required to fix was changing the default`transitioningBoxSelect: true` to false.  It was meant to reduce re-rendering, but overlooked this case. To test, try on it on any study and ensure scatterplot filters.
4) The logic to disable negative log 10 transform and for determining the min/max of scatterplot axis was changed to IGNORE 0 values.  From a holistic standpoint, in the scatterplot "options", users should have the ability to do a -log10 transformation on the data only when ALL NUMERIC DATA is greater than or …
> [IPAD-447] set analysis, log transform adjustments

- package-lock.json
- package.json
- src/components/Differential/DifferentialDetail.jsx
- src/components/Enrichment/SplitPanesContainer.jsx
react-split-pane is deprecated and when using with React 17 (or 18), throws errors when running the latest versions of npm (higher than 8.5.5). This task swaps it out for [react-split-pane-r17](https://www.npmjs.com/package/react-split-pane-r17), as suggested on this [thread](https://github.com/decaporg/decap-cms/pull/6137). This way we don't need to resort to suggesting _npm install --legacy-peer-deps_
> [AU-450] Swap react-split-pane module

- package-lock.json
- package.json
- public/manifest.json
- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/MetafeaturesTable.jsx
- src/components/Differential/MetafeaturesTableDynamic.jsx
- src/components/Differential/ScatterPlot.jsx
- src/components/Differential/ScatterPlotDiv.jsx
- src/components/Enrichment/Enrichment.jsx
- src/components/Enrichment/FilteredDifferentialTable.jsx
- src/components/Shared/helpers.jsx
- src/components/Tabs.jsx
1) When calculating our column types, we find the first value for each column with a value that is not null, and empty string, "NA". "-Inf" and "Inf" were a part of a new study and broke the function, as they can make a numeric column be read as alphanumeric.  Now corrected, "Inf" will show up in the datatable as a blank, since it is not a number.
2) Also, we have a reusable function (**getMaxAndMin**) that is used to create scatterplot axis and determine if an axis can be -log 10 transformed.  That function was creating a min/max array (e.g. [0, 1] based on the values in the first object in the array. However, if the first object has null values or "Inf", the calculation was flawed. **The function has been adjusted to only run a calculation for numbers**.  Additionally, in the instance …
> [IPAD-458] adjust -log10 transformations, handle infinity

- src/components/Differential/Differential.jsx
- src/components/Differential/DifferentialDetail.jsx
- src/components/Differential/ScatterPlot.jsx
- src/components/Differential/ScatterPlotDiv.jsx
- src/components/Enrichment/Enrichment.jsx
Adjustment allows for multi-feature selection on scatter plot and data table (in the differential tab), even if that study does not have multi-feature plots.  To test, interact with the scatter plot and table for studies with (example study) and without multi-feature plots.
> [IPAD-459] always allow multi-feature selection

- package-lock.json
- package.json
- public/manifest.json
- src/components/App.scss
- src/components/Tabs.jsx
Display an overlay when the screen width is under 1024 pixels, so users do not have a substandard experience on small devices.
> [IPAD-478] - Landing Page for Smaller Devices

- .github/workflows/dev.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
GitHub will soon require that all Actions run with Node 20
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
https://github.com/actions/checkout/releases/tag/v4.0.0
https://github.com/peter-evans/repository-dispatch/releases/tag/v3.0.0
https://github.com/actions/setup-node/releases/tag/v4.0.0
You can see example deprecation warnings in one of our recent runs:
https://github.com/abbvie-external/OmicNavigatorWebApp/actions/runs/8147004420
> Migrate GitHub Actions to Node 20
